### ISSUE TITLE
What exactly does cordova-overlay do?

### ISSUE THREAD

**Issue by druidtton** [z0rkuM/cordova-overlay#1]
Hello, I saw that there is very minimal documentation on this plugin, and I wanted to know what this plugin does and what it doesn't do.

Does this create an HTML webview overlaying other apps?
Does it create a webview over the cordova webview?

Thank you for answering.

Hola, vi que hay minima informacion de este plugin y queria saber que es lo que hace y lo que no hace ya que estoy buscando algo para mi app.

Crea un overlay sobre de otros apps?
O solo crea un overlay de HTML encima de cordova?

Gracias por tu respuesta.

**Comment by z0rkuM** [comment]
Hi, the plugin creates a native webview overlaying any app, you just need to send the html content from your cordova app. At this moment, it hasn't got any configuration option or documentation because I won't use it in my main app.
